language: python
sudo: required
cache: pip
env:
  global:
  - PYTHONUNBUFFERED=yes
matrix:
  include:
  - python: 3.7.0
    env: TOXENV=flake8
    os: linux
    dist: xenial
  - python: 3.7.0
    env: TOXENV=typecheck
    os: linux
    dist: xenial
  - python: 3.5.0
    env: TOXENV=3.5 IDENT="3.5.0" RUN_SUITE=y USE_PYENV=y
    os: linux
  - python: 3.6.0
    env: TOXENV=3.6 IDENT="3.6.0" RUN_SUITE=y USE_PYENV=y
    os: linux
  - python: 3.7.0
    env: TOXENV=3.7 IDENT="3.7.0" RUN_SUITE=y USE_PYENV=n
    os: linux
    dist: xenial
  - python: 3.7.1
    env: TOXENV=3.7 IDENT="3.7.1" RUN_SUITE=y USE_PYENV=n
    os: linux
    dist: xenial
before_install:
install:
- |
  if [[ $USE_PYENV ]]; then
      git clone https://github.com/yyuu/pyenv.git ~/.pyenv
      PYENV_ROOT="$HOME/.pyenv"
      PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      pyenv install "${IDENT}"
      pyenv global "${IDENT}"
  fi
- pip list
- travis_retry pip install -U tox
after_success:
- |
  if [[ ! -z "$IDENT" ]]; then
      .tox/$TOXENV/bin/coverage xml
      .tox/$TOXENV/bin/codecov -e IDENT
  fi;
script: tox -v -- -v
